---
version: '3'

services:
  job-cluster:
    build: .
    container_name: job-cluster
    ports:
      - "8081:8081"
      - "9249:9249"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: job-cluster

  taskmanager1:
    build: .
    container_name: taskmanager1
    depends_on:
      - job-cluster
    command: taskmanager
    ports:
      - "9250:9249"
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: job-cluster
        taskmanager.numberOfTaskSlots: 2

  taskmanager2:
    build: .
    container_name: taskmanager2
    depends_on:
      - job-cluster
    command: taskmanager
    ports:
      - "9251:9249"
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: job-cluster
        taskmanager.numberOfTaskSlots: 2

  prometheus:
    image: prom/prometheus:v2.25.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/flink.rules.yml:/etc/prometheus/flink.rules.yml

  grafana:
    image: grafana/grafana:7.4.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=flink
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/

volumes:
  state:

